### ISSUE TITLE
Construir el Pitch de Identificación del problema a resolver

### ISSUE THREAD

**Issue by cmtecnica10** [Anghy1910/Equipo1_FO_PPI2020#1]
Discurso que vamos a presentar para la valoración de la idea y aceptación de la propuesta

**Comment by Anghy1910** [comment]
24/06/2020 Se realizó el discurso del Pitch segun guia mandada por asesor

**Comment by Anghy1910** [comment]
Se aplaza para la semana del 06/07  al 10/07

**Comment by Anghy1910** [comment]
Se realizo con exito el 06/07
